#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-pdfCluster
Version  : 1.0.4
Release  : 51
URL      : https://cran.r-project.org/src/contrib/pdfCluster_1.0-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/pdfCluster_1.0-4.tar.gz
Summary  : Cluster Analysis via Nonparametric Density Estimation
Group    : Development/Tools
License  : GPL-2.0
Requires: R-pdfCluster-lib = %{version}-%{release}
Requires: R-geometry
BuildRequires : R-geometry
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
estimation is performed. Operationally, the kernel method is used throughout to estimate
   the density. Diagnostics methods for evaluating the quality of the clustering 
   are available. The package includes also a routine to estimate the 
   probability density function obtained by the kernel method, given a set of
   data with arbitrary dimensions.

%package lib
Summary: lib components for the R-pdfCluster package.
Group: Libraries

%description lib
lib components for the R-pdfCluster package.


%prep
%setup -q -n pdfCluster
pushd ..
cp -a pdfCluster buildavx2
popd
pushd ..
cp -a pdfCluster buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737152530

%install
export SOURCE_DATE_EPOCH=1737152530
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pdfCluster/CHANGELOG
/usr/lib64/R/library/pdfCluster/CITATION
/usr/lib64/R/library/pdfCluster/DESCRIPTION
/usr/lib64/R/library/pdfCluster/INDEX
/usr/lib64/R/library/pdfCluster/Meta/Rd.rds
/usr/lib64/R/library/pdfCluster/Meta/data.rds
/usr/lib64/R/library/pdfCluster/Meta/features.rds
/usr/lib64/R/library/pdfCluster/Meta/hsearch.rds
/usr/lib64/R/library/pdfCluster/Meta/links.rds
/usr/lib64/R/library/pdfCluster/Meta/nsInfo.rds
/usr/lib64/R/library/pdfCluster/Meta/package.rds
/usr/lib64/R/library/pdfCluster/NAMESPACE
/usr/lib64/R/library/pdfCluster/NEWS.md
/usr/lib64/R/library/pdfCluster/R/pdfCluster
/usr/lib64/R/library/pdfCluster/R/pdfCluster.rdb
/usr/lib64/R/library/pdfCluster/R/pdfCluster.rdx
/usr/lib64/R/library/pdfCluster/data/oliveoil.rda
/usr/lib64/R/library/pdfCluster/data/wine.rda
/usr/lib64/R/library/pdfCluster/help/AnIndex
/usr/lib64/R/library/pdfCluster/help/aliases.rds
/usr/lib64/R/library/pdfCluster/help/paths.rds
/usr/lib64/R/library/pdfCluster/help/pdfCluster.rdb
/usr/lib64/R/library/pdfCluster/help/pdfCluster.rdx
/usr/lib64/R/library/pdfCluster/html/00Index.html
/usr/lib64/R/library/pdfCluster/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/pdfCluster/libs/pdfCluster.so
/V4/usr/lib64/R/library/pdfCluster/libs/pdfCluster.so
/usr/lib64/R/library/pdfCluster/libs/pdfCluster.so
